<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/03 22:42:48
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
